### ISSUE TITLE
pose_stats file

### ISSUE THREAD

**Issue by yxin-zhang** [liw95/DiffLoc#3]
Thanks for your excellent work! Could you provide the pose_stats.txt file for the NCLT dataset? When I reproduced it, the RTE could not reach the level mentioned in the article, and the visualization results were skewed, but the RRE was normal. I think this may be caused by the incorrect mean_t and std_t.
![trajectory](https://github.com/user-attachments/assets/80ba596e-f609-4cb0-912e-9998036d4df0)

**Comment by liw95** [comment]
Hi,
Thank you for your interest. Of course, you can! Here is the content of pose_stats.txt:
-104.2464047 -381.2804443 8.2290920
118.8724964 193.5478438 4.8854634

**Comment by yxin-zhang** [comment]
Thank you for your prompt reply! It helps a lot!
